In [5]:
import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import sys, os

# sys.path.append(os.path.dirname(os.path.dirname(__file__)))
# from utils import (
#     load_csv
# )

data = pd.DataFrame({
    "Product": ["A", "B", "C"],
    "Sales": [120, 180, 150]
})

sample_data = pd.read_csv("../../jordan/dashboard/test2.csv")

# module usage rate

# myth v.s. fact quiz answers

# create a dataframe measuring the number of correct answers for each question

questions = ["question0", "question1", "question2", "question3", "question4", "question5", "question6", "question7", "question8", "question9"]
question_answer_counts_df = pd.DataFrame(columns=["Question", "Correct Answers"])

In [6]:
for i in questions:
    # create row
    new_row = pd.DataFrame({"Question": [i], "Correct Answers": [(sample_data[i] >= 1).sum()]})
    question_answer_counts_df = pd.concat([question_answer_counts_df, new_row], ignore_index=True)

question_answer_counts_df.head(5)

    Question Correct Answers
0  question0              40
1  question1              34
2  question2              34
3  question3              37
4  question4              37

In [7]:
# List of target column names
module_cols = [f"module{i}" for i in range(8)]

# Sum the values along axis 1 (rows)
sample_data["Total Cards Completed"] = sample_data[module_cols].sum(axis=1)

sample_data['Total Cards Completed'].head(5)

0    7
1    7
2    3
3    7
4    4
Name: Total Cards Completed, dtype: int64

In [8]:
random_sample = sample_data.sample(n=35, random_state=1)
# set all module columns to true
random_sample.loc[:, "module0":"module7"] = 1

sample_data.update(random_sample)

sample_data.head(10)

,id,module0,module1,module2,module3,module4,module5,module6,module7,question0,question1,question2,question3,question4,question5,question6,question7,question8,question9,Total Cards Completed
0,14484439,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,7
1,14868076,1,1,1,1,0,1,1,1,1,0,1,0,1,1,1,1,1,0,7
2,19892941,1,1,1,1,1,1,1,1,0,1,1,0,1,1,1,0,0,1,3
3,16683858,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,7
4,13940457,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,0,1,4
5,13715816,1,0,1,0,1,1,1,1,1,1,0,1,1,1,1,1,0,1,6
6,15340761,1,1,1,1,0,0,1,1,0,0,1,1,0,1,1,1,1,0,6
7,12452021,1,1,1,0,0,1,0,0,1,0,0,1,1,0,1,1,0,0,4
8,15980810,1,1,0,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,5
9,16674342,1,0,0,0,0,0,0,1,1,0,1,0,0,0,1,1,1,1,2